CC := cc
CFLAGS := -Wall -Wextra -Werror
SRC := ft_db.c ft_string.c ft_parse.c ft_print.c ft_shittinette.c rush-02.c
RSLT := rush02

all: $(RSLT)

$(RSLT): 
	$(CC) $(CFLAGS) $(SRC) -o $(RSLT)

clean:
	rm $(RSLT)
